version: "3.8"
services:
  api-server:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
       - mongodb
  mongodb:
    image : mongo
    container_name: mongodb
    ports :
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password




